
export const metadata = {
    title: 'Translate',
    description: 'Generated by create next app',
}

export default function AdminLayout({ children }) {
    return (
        <html lang="en">  
            <body>
            <h2>here i am shimaa hello hooo </h2>

                {children}
            </body>
        </html>
    )
}
