
import AdminNavbar from '@/components/adminDashboard/AdminNavbar'
import Sidebar from '@/components/adminDashboard/Sidebar'
import { Inter } from 'next/font/google'
import { redirect } from 'next/navigation'
import { Toaster} from 'sonner'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Translation',
  description: 'Generated by create next app',
}
export default function AdminLoyout({ children }) {
 const userAuth = true;

  return (
    <>
    {userAuth ? <div className={inter.className}>
  
        <div  >
          <AdminNavbar />
          <div className='be-red-600 pt-16 lg:ps-64 md:ps-64 ' >
          {children}
          <Toaster richColors  position="top-right" />
          </div>
        </div>
        <div className=''>
          <Sidebar />
        </div>
      </div>:
      redirect('/login')
      }
  
    </>

  )
}

