
import Navbar from '@/components/navbar/Navbar'
import './globals.css'

export const metadata = {
  title: 'Translate',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  >
      <Navbar/>
      <div className='pt-16'>
      {children}
      </div>
     
        </body>
    </html>
  )
}
